### ISSUE TITLE
activation

### ISSUE THREAD

**Issue by nlienard** [Aymkdn/assistant-transport-montpellier#2]
Salut
pour accéder à ce module, il est demandé d'ouvrir une issue, ce que je fais :)
Merci

**Comment by Aymkdn** [comment]
En fait c'est plutôt pour le configurer ;-)

Il faut donc me dire quel arrêt de bus et/ou tram tu veux connaitre, et dans quelle direction.

Par exemple : `le tram L3, arrêt Port Marianne, en direction de Lattes`

**Comment by nlienard** [comment]
Tram L3, arrêt Perols ETang de L'or, en direction de Gare Saint Roch
ca serait parfait.
merci
(et me dire ou le modifier pour que je le fasse moi même ^^)

**Comment by Aymkdn** [comment]
Tu mets combien de temps pour aller de chez toi au tram ? Car on peut aussi spécifier un délai. Par exemple j'habite à 5 minutes du tram, donc Google Home ne me donne pas les trams qui arrivent dans moins de 5 minutes car je ne pourrai pas les avoir.

Et ensuite oui je t'explique quoi faire :-)

**Comment by Aymkdn** [comment]
Tu crées une nouvelle applet IFTTT avec en entrée Google Assistant, puis en sortie tu utilises Pushbullet Note avec ces informations : 
  - Title: **Assistant**
  - Message: **transport-montpellier_{'delay':5, 'arrivalCitywayId':43101, 'directionForTam':'FORWARD', 'lineCitywayId':22, 'lineId':3, 'lineUrban':1, 'stopCitywayId':43201, 'stopId':1274}**

Tu peux remplacer le `'delay':5` par le délai que tu veux donc.

**Comment by nlienard** [comment]
Merci ! en l'état, ca marche nikel.
Après j'aurais préféré que GH répond directement les horaires plutôt que le nombre de minutes des 3 prochains tram.
Ca se conf à quel endroit ?
Merci!

**Comment by Aymkdn** [comment]
Ça ne se configure pas... Moi je préfère savoir dans combien de temps le tram arrive pour savoir si je dois me speeder ^^

**Comment by Aymkdn** [comment]
Et aussi ça récupère les données de la TAM sur le temps restant en live (comme l'application mobile qui te dit dans combien de temps arrive le prochain tram). Du coup c'est la façon dont c'est indiqué ici !

Je ferme l'issue donc :-)

**Comment by nlienard** [comment]
je confirme c'est fonctionnel !
merci
