### ISSUE TITLE
Je voudrais la même chose, mais pour Nantes

### ISSUE THREAD

**Issue by Pyrosfr** [Aymkdn/assistant-transport-montpellier#3]
A priori, toutes les infos sont disponibles : https://data.nantes.fr/fileadmin/nm_opendata/pdf/Semitan-Documentation-API-V3.pdf

Donc l'idée de voir si je peux réaliser un portage en se basant sur ces open data pour le mettre ensuite à disposition

**Comment by Aymkdn** [comment]
OK, fais toi plaisir 😉

**Comment by Aymkdn** [comment]
Je ferme cet issue et n'hésite pas à quand même poser tes questions ici si tu en as ;-)
