### ISSUE TITLE
Intéressé pour utiliser les horaires de tram

### ISSUE THREAD

**Issue by ewidance** [Aymkdn/assistant-transport-montpellier#4]
Bonjour,

Super boulot sur assistant.. Ca marche à merveille avec la freebox. Je serai intéressé pour utiliser les horaires du tram, mais aparemment, il me manquerait un bout.. Comment procéder? 

JP CIVADE / jp@civade.com

**Comment by Aymkdn** [comment]
Il faut me dire l'arrêt de tram, la ligne de tram concernée, ainsi que la direction.

Par exemple : "esplanade de l'Europe, ligne 1, direction Odysseum"

**Comment by Aymkdn** [comment]
@ewidance  ?

**Comment by ewidance** [comment]
Oui sorry :)... Notre dame de Sablassous direction Odysseum...

**Comment by Aymkdn** [comment]
Donc c'est pour la ligne de bus 37 qui va à Place de l'Europe ?

**Comment by Aymkdn** [comment]
Car y'a pas de tram ni de bus qui vont à Odysseum depuis de Notre Dame de Sablassou...

**Comment by Aymkdn** [comment]
Éventuellement la ligne 2 de tram qui va à Jacou ou St Jean de Védas ou Sabines.... Mais y'a pas la ligne 1 qui va à Odysseum.

**Comment by ewidance** [comment]
Oui, Tramway ligne 2 c'est ca :)..

**Comment by Aymkdn** [comment]
Mais quelle direction ?????

**Comment by ewidance** [comment]
Désolé je suis en pointillé car au taf.. Direction Centre ville (mosson)

**Comment by Aymkdn** [comment]
Moi j'ai trois destinations pour le tram 2 depuis Sablassou :
  1) Jacou, 
  2) St Jean de Védas, 
  3) Sabines.

Tu dois choisir une de ces trois options. J'imagine que c'est Jacou ?

**Comment by Aymkdn** [comment]
Tu dois créer une [nouvelle applet IFTTT](https://ifttt.com/create) avec en entrée (**this**) `Google Assistant` et la phrase que tu veux (par exemple `trouve le prochain tram pour Jacou`), puis en sortie (**that**) tu utilises `Pushbullet Note`, avec les informations ci-dessous (pour *ligne 2, arrêt "Notre Dame de Sablassou", direction Jacou*) : 

  - Title: **Assistant**
  - Message: **transport-montpellier_{'delay':5, 'arrivalCitywayId':42169, 'directionForTam':'FORWARD', 'lineCitywayId':12, 'lineId':2, 'lineUrban':1, 'stopCitywayId':42159, 'stopId':1215}**

Le `delay` (en minutes) permet de ne pas donner les trams avant le délai indiqué. Par exemple, j'habite à 5 minutes du tram (d'où le `'delay':5`), donc je ne veux savoir que les trams qui arrivent dans plus de 5 minutes.

![capture](https://user-images.githubusercontent.com/946315/37968836-89117686-31cf-11e8-8f63-458dd119ad53.PNG)

**Comment by ewidance** [comment]
Je  vois la méthode, j'ai testé et cela semble marcher.. Mais en fait c'est plutot pour aller en direction de St Jean de Vedas... Du coup j'ai essayé de trouver les valeurs des paramètres, mais pas simple. LineId correspond à la ligne, LineUrban au fait que cela soit un tramway, delay je vois aussi, mais pour arrivalCitywayId stopCitywayId directionForTam et stopId je ne vois vraiment pas ou tu les choppes... J'ai bien essayer de capter le contenu de STOP_ON_LINE.json mais, sans succès... Comment cela marche t'il?

**Comment by Aymkdn** [comment]
Tu as regardé dans le bon fichier, mais j'avoue que les données de la TAM ne sont pas très lisibles....

Moi j'y cherche `"stopName": "Notre-Dame de Sablassou"` puis je regarde le `arrivalName` et le `LineId`.

Pour St Jean de Védas comme destination : 
**transport-montpellier_{'delay':5, 'arrivalCitywayId':42101, 'BACKWARD':'FORWARD', 'lineCitywayId':12, 'lineId':2, 'lineUrban':1, 'stopCitywayId':42211, 'stopId':1223}**

**Comment by ewidance** [comment]
Yes :).. Merci!
