### ISSUE TITLE
Conf pour mon emplacement

### ISSUE THREAD

**Issue by hotplug** [Aymkdn/assistant-transport-montpellier#5]
Salut,

tout d'abord , super boulot pour la partie Freebox ;)
Peux tu stp me fournir la conf pour : 
- ligne 2, arrêt "La galine", direction Jacou et Notre Dame de Sablassou
et accessoirement, comment on fait pour confer 2 direction :) ?
- ligne 2, arrêt "La galine", direction Saint-Jean de Védas et  Sabines

Merci !

**Comment by Aymkdn** [comment]
Salut,

Tu dois créer une nouvelle applet IFTTT avec en entrée `Google Assistant` et la phrase que tu veux (par exemple `trouve le prochain tram pour Jacou`), puis en sortie tu utilises `Pushbullet Note`, avec les informations ci-dessous selon ce que tu souhaites : 

- *ligne 2, arrêt "La galine", direction Jacou*
  - Title: **Assistant**
  - Message: **transport-montpellier_{'delay':5, 'arrivalCitywayId':42169, 'directionForTam':'FORWARD', 'lineCitywayId':12, 'lineId':2, 'lineUrban':1, 'stopCitywayId':42155, 'stopId':1213}**

- *ligne 2, arrêt "La galine", direction Notre Dame de Sablassou*
  - Title: **Assistant**
  - Message: **transport-montpellier_{'delay':5, 'arrivalCitywayId':42159, 'directionForTam':'FORWARD', 'lineCitywayId':12, 'lineId':2, 'lineUrban':1, 'stopCitywayId':42155, 'stopId':1213}**

- *ligne 2, arrêt "La galine", direction Saint-Jean de Védas*
  - Title: **Assistant**
  - Message: **transport-montpellier_{'delay':5, 'arrivalCitywayId':42101, 'directionForTam':'BACKWARD', 'lineCitywayId':12, 'lineId':2, 'lineUrban':1, 'stopCitywayId':42215, 'stopId':1225}**

- *ligne 2, arrêt "La galine", direction  Sabines*
  - Title: **Assistant**
  - Message: **transport-montpellier_{'delay':5, 'arrivalCitywayId':42259, 'directionForTam':'BACKWARD', 'lineCitywayId':12, 'lineId':2, 'lineUrban':1, 'stopCitywayId':42215, 'stopId':1225}**

Le `delay` (en minutes) permet de ne pas donner les trams avant le délai indiqué. Par exemple, j'habite à 5 minutes du tram (d'où le `'delay':5`), donc je ne veux savoir que les trams qui arrivent dans plus de 5 minutes.

**Comment by hotplug** [comment]
J'ai du louper une étape je pense.
Je mets quoi dans la config de l'applet IFTTT sur "What do you want the Assistant to say in response?"

Dans l'état , je pose ma question.
Google Home répond : "OK , action en cours"

Le log de l'appli dit bien : 

>  [assistant] Commande reçue:  [ 'transport-montpellier_{\'delay\':5, \'arrivalCitywayId\':42169, \'directionForTam\':\'FORWARD\', \'lineCitywayId\':12, \'lineId\':2, \'lineUrban\':1, \'stopCitywayId\':42155, \'stopId\':1213}' ]
[assistant] Appelle du plugin 'transport-montpellier'
[assistant-transport-montpellier] Recherche des prochains tram pour la ligne 2
[assistant-transport-montpellier] le prochain tram est dans 44 minutes

Mais je n'ai pas de réponse vocale de la Google home.

**Comment by Aymkdn** [comment]
Il faut installer [notifier](https://aymkdn.github.io/assistant-plugins/?plugin=notifier)

**Comment by hotplug** [comment]
Ok, merci , Ca fonctionne !

Dans le  "arrivalCitywayId", c'est une direction ou un arrêt ?
Si c'est un arrêt, il me suffirait de choisir le bon arrêt , et je n'aurai pas besoin de poser 2 fois la question si l'arrêt en question est avant la bifurcation du tram.

**Comment by Aymkdn** [comment]
Toutes les informations viennent de https://github.com/Aymkdn/assistant-transport-montpellier/blob/master/STOP_ON_LINE.json

**Comment by hotplug** [comment]
Ok, du coup, pour la TAM, c'est "2 lignes différentes" sur toutes les stations de la ligne 2 , par exemple, alors qu'ils vont dans la même direction. Vraiment étrange.
Tant pis, je vais faire 2 applet et j'appellerai les 2 à chaque fois :)
Merci de ton aide !
