### ISSUE TITLE
Utilisation pour Lyon

### ISSUE THREAD

**Issue by Aquaxoc** [Aymkdn/assistant-transport-montpellier#6]
Bonjour,
Je trouve l'idée excellente et j'aimerais la porter pour le réseau TCL de Lyon pour avoir des informations sur les temps de passage des prochains bus/trams/métros.
Est-il donc possible de s'en servir avec un JSON qu'on récupère par un quelconque moyen ?

**Comment by Aymkdn** [comment]
Oui tu peux utiliser n'importe quelle source, mais tu devras créer ton propre plugin en utilisant https://github.com/Aymkdn/assistant-template

Tu peux aussi t'inspirer du code de https://github.com/Aymkdn/assistant-transport-montpellier

Si t'as besoin d'aide durant le développement, n'hésite pas à me demander :-)

Une fois ton plugin fonctionnel, dis le moi et je pourrai l'ajouter à la liste des plugins disponibles !

**Comment by Aquaxoc** [comment]
Super merci 👍
