### ISSUE TITLE
Utilisation

### ISSUE THREAD

**Issue by n-rocher** [Aymkdn/assistant-transport-montpellier#8]
Bonjour,
Je suis intéressé pour l'utiliser, peux tu me donner plus de détails ?

Merci ;)

**Comment by Aymkdn** [comment]
Faut me dire le nom de la station où tu es et quelle ligne t'intéresse, et dans quelle direction.

**Comment by n-rocher** [comment]
J'aimerais adapter le système pour Nantes et j'essaie de comprendre comment
ça marche.

Donc disons un arrêt connu de Montpellier avec la direction vers le nord
ahah.

Merci

**Comment by Aymkdn** [comment]
Ah dans ce cas c'est différent.... Si tu veux ça pour Nantes il faut créer ton propre plugin et le partager avec la communauté (ça, c'est pas obligé, mais c'est mieux !). Te donner le JSON d'un arrêt de tram à Montpellier ne servira à rien donc car cette information est spécifique pour Montpellier seulement...

**Comment by Aymkdn** [comment]
Je donne deux ressources avec lesquelles tu peux commencer :
 - https://data.nantesmetropole.fr/explore/dataset/244400404_api-temps-reel-tan/information/
 - https://www.navitia.io/

Pour courage !
